export {
  ConfigError,
  DEFAULT_CONCURRENCY,
  DEFAULT_COOLDOWN_MS,
  DEFAULT_KILL_GRACE_MS,
  DEFAULT_MAX_ATTEMPTS,
  DEFAULT_RATE_LIMIT_PATTERNS,
  DEFAULT_TIMEOUT_SEC,
  DEFAULT_TRIALS,
  V1_ROSTER,
  apiEquivalentCostUsd,
  defaultRunConfig,
  loadRunConfig,
  resolveRunConfig,
  selectConfigs,
  type AgentConfig,
  type RateWindowConfig,
  type NotionConfig,
  type ResolvedRunConfig,
  type RunConfigFile,
} from './config.js';

export {
  DEFAULT_NOTION_API_BASE,
  LIVE_LIB_ENV,
  LiveFixtures,
  POINTER_FILENAME,
  RUN_LOG_FILENAME,
  appendRunLog,
  inspectLiveTasks,
  isLiveTask,
  liveRequirementProblems,
  loadLiveLib,
  renderLiveProblems,
  resolveLiveLibDir,
  resolveLiveSettings,
  specPathFor,
  type LiveFixture,
  type LiveFixturesOptions,
  type LiveLib,
  type LiveNotionClient,
  type LiveSettings,
  type LiveTaskInfo,
  type NotionSettings,
  type ProvisionedFixture,
} from './live.js';

export {
  Checkpoint,
  STATE_VERSION,
  buildCells,
  cellKey,
  newRunId,
  parseCellKey,
  resume,
  trialDirFor,
  type CellCoords,
  type CellScore,
  type CellState,
  type CellStatus,
  type RunMeta,
  type RunStateFile,
} from './checkpoint.js';

export {
  UNSCORABLE_STATUSES,
  isScorable,
  scoreTrial,
  toTrialRecord,
  unscoredRecord,
  type ScoreTrialOptions,
  type ScoredTrial,
} from './score.js';

export {
  buildPlan,
  renderPlan,
  type BuildPlanOptions,
  type LivePlan,
  type OrderPlan,
  type WatchdogPlan,
  type PlanEnv,
  type PlannedConfig,
  type PlannedTask,
  type ResumePlan,
  type RunPlan,
} from './plan.js';

export {
  DEFAULT_ORDER,
  LEGACY_ORDER,
  ORDER_POLICIES,
  axesFromCells,
  blocksOf,
  cellRanker,
  describeOrder,
  isOrderPolicy,
  orderCells,
  parseOrder,
  type OrderAxes,
  type OrderPolicy,
} from './order.js';

export {
  ACKNOWLEDGEABLE_KINDS,
  AckError,
  NEVER_ACKNOWLEDGEABLE_KINDS,
  ackFlag,
  ackKey,
  buildAcknowledgments,
  describeAck,
  isAcknowledgeableKind,
  matchAck,
  mergeAcknowledgments,
  newAcknowledgments,
  parseAckFlags,
  parseAckSpec,
  renderAcknowledgments,
  requireAckReason,
  type AckSignature,
  type AckSpec,
  type AckTarget,
  type Acknowledgment,
  type BuildAckOptions,
} from './ack.js';

export {
  ALERT_FILENAME,
  ALERT_FILE_VERSION,
  DEFAULT_WATCHDOG_SETTINGS,
  WATCHDOG_EXIT_CODE,
  Watchdog,
  alertPath,
  freeDiskBytes,
  longestCommonSubstring,
  normalizeDiagnostic,
  readAlertFile,
  renderAlertBanner,
  resolveWatchdogSettings,
  sharedEvidence,
  writeAlertFile,
  type AlertFile,
  type AlertKind,
  type AlertLevel,
  type InfrastructureSnapshot,
  type SharedEvidence,
  type WatchdogAlert,
  type WatchdogObservation,
  type WatchdogOptions,
  type WatchdogSettings,
} from './watchdog.js';

export {
  buildDoctorReport,
  isVerifierCrash,
  renderDoctorReport,
  type DoctorAcknowledgment,
  type DoctorConfigRow,
  type DoctorFinding,
  type DoctorOptions,
  type DoctorReport,
  type DoctorTask,
} from './doctor.js';

export {
  RUN_SPEC_FILENAME,
  RUN_SPEC_VERSION,
  cellKeySet,
  createRunSpec,
  describeGrid,
  detectDrift,
  diffGrid,
  driftLines,
  expandSpec,
  gridCells,
  hashConfigs,
  isSeriousDrift,
  readRunSpec,
  reconstructSpec,
  recordAcks,
  recordDrift,
  recordRedo,
  renderRefusal,
  runSpecPath,
  specAcknowledgments,
  specCells,
  writeRunSpec,
  type ConfigDrift,
  type CreateSpecOptions,
  type DriftKind,
  type GridDiff,
  type Reconstruction,
  type RequestedAxes,
  type RunSpecExecution,
  type RunSpecFile,
  type RunSpecGrid,
  type RunSpecHistoryEntry,
  type RunSpecProvenance,
  type SpecConfig,
} from './run-spec.js';

export {
  DEFAULT_MAX_RATE_LIMITED_ATTEMPTS,
  RATE_WINDOW_STATE_FILENAME,
  Scheduler,
  rateWindowStatePath,
  readRateWindowState,
  runQueue,
  writeRateWindowState,
  type CellOutcome,
  type Decision,
  type QueueCell,
  type RateWindowState,
  type RunQueueOptions,
  type SchedulerEvent,
  type SchedulerOptions,
} from './queue.js';

export {
  DEFAULT_HOST,
  DEFAULT_PORT,
  STATUS_SCHEMA_VERSION,
  StatusSource,
  buildStatus,
  createStatusServer,
  dashboardUrl,
  defaultWebRoot,
  generateKey,
  serve,
  type ConfigStatus,
  type ServeHandle,
  type ServeOptions,
  type StatusAlert,
  type StatusConfig,
  type StatusFailure,
  type StatusInput,
  type StatusPayload,
  type StatusResult,
  type StatusTrial,
} from './serve.js';

export {
  STRIPPED_ENV_KEYS,
  buildTrialEnv,
  clearVersionCache,
  getCliVersion,
  redactedEnvKeys,
  runTrial,
  writeJsonAtomic,
  type RunTrialOptions,
  type TrialIdentity,
  type TrialOutcome,
  type TrialStatus,
} from './spawn.js';

export {
  LineSplitter,
  TranscriptWriter,
  parseTranscript,
  readTranscript,
  type ReadTranscript,
  type TranscriptRecord,
  type TranscriptStream,
} from './transcript.js';

export {
  UnknownHarnessError,
  claudeCodeAdapter,
  codexAdapter,
  getAdapter,
  hasAdapter,
  normalizeClaudeUsage,
  normalizeCodexUsage,
  reconcileCodexUsages,
  registerAdapter,
  type HarnessAdapter,
  type Invocation,
  type InvocationContext,
  type ParsedTranscript,
  type RateLimitSignal,
} from './parsers/index.js';

export {
  compilePatterns,
  cooldownFor,
  scanForRateLimit,
  type CompiledPatterns,
} from './rate-limit.js';

export {
  PROMPT_FILENAME,
  discoverTasks,
  globToRegExp,
  loadTask,
  matchesAny,
  parseFrontmatter,
  promptBody,
  readPrompt,
  taskSpecFromFrontmatter,
} from './tasks.js';

export { TokenPool, type TokenLease } from './token-pool.js';

export {
  DOCS_CONDITIONS,
  emptyUsage,
  type DocsCondition,
  type HarnessId,
  type TaskFamily,
  type TaskRuntime,
  type TaskSpec,
  type TaskStage,
  type TaskSuite,
  type TokenUsage,
} from './types.js';
